//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis_Web.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNTAKIP
    {
        public int TAKIPID { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SERİNO { get; set; }
    }
}
